---
- name: Query Criteria
  block:
    - name: Debug criteria job
      ansible.builtin.debug:
        msg: "DEBUG: criteria job --->{{ criteria_job }}<---"

    - name: Debug reported jobs
      ansible.builtin.debug:
        msg: "DEBUG: dlrnapi reported jobs --->{{ reported_jobs.stdout | from_json }}<---"

    - name: Debug json query result
      vars:
        query: "[?contains(job_id, '{{ criteria_job }}')]"
      ansible.builtin.debug:
        msg: "DEBUG: json query result --->{{ reported_jobs.stdout | from_json | json_query(query) }}<---"

    - name: Criteria failed?
      ansible.builtin.fail:
        msg: "FAILURE! :( Promotion criteria failed to match."
      vars:
        query: "[?contains(job_id, '{{ criteria_job }}')]"
      when: reported_jobs.stdout | from_json | json_query(query) == []

    - name: Criteria match?
      ansible.builtin.debug:
        msg: "SUCCESS! :) Promotion criteria match!"
      vars:
        query: "[?contains(job_id, '{{ criteria_job }}')]"
      when: reported_jobs.stdout | from_json | json_query(query) != []
