---
- hosts: all
  gather_facts: true
  tasks:
    - name: Run Podified EDPM deployment
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework"
        cmd: >-
          ansible-playbook deploy-edpm.yml
          -e @scenarios/centos-9/base.yml
          -e @scenarios/centos-9/edpm_ci.yml
          {%- if 'edpm-ansible' in zuul_change_list %}
          -e @{{ ansible_user_dir }}/ci-framework/edpm-ansible.yml
          {%- endif %}
          {%- if cifmw_extras is defined %}
          {%-   for extra_var in cifmw_extras %}
          -e "{{   extra_var }}"
          {%-   endfor %}
          {%- endif %}
          -e @scenarios/centos-9/zuul_inventory.yml
