---
- name: List all of the existing virtual machines
  ignore_errors: true
  register: vms_list
  community.libvirt.virt:
    command: list_vms
    uri: "qemu:///system"

- name: Filter out edpm vm
  ignore_errors: true
  ansible.builtin.set_fact:
    edpm_vm: "{{ vms_list.list_vms | select('match', '^edpm-.*$') }}"

- name: Generate logs on EDPM vms
  when:
    - '"edpm-compute-0" in edpm_vm'
  block:
    - name: Generate logs on edpm vm
      ignore_errors: true
      ci_script:
        output_dir: "{{ cifmw_artifacts_basedir }}/artifacts"
        script: |-
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i {{ cifmw_artifacts_basedir }}/artifacts/edpm/ansibleee-ssh-key-id_rsa root@192.168.122.100 <<EOF
          set -xe;
          mkdir -p /tmp/{{ edpm_vm[0] }}
          cp -r /var/log/ /tmp/{{ edpm_vm[0] }}
          cp -r /var/lib/openstack /tmp/{{ edpm_vm[0] }}
          cp -r /var/lib/config-data /tmp/{{ edpm_vm[0] }}
          cp -r /var/lib/cloud /tmp/{{ edpm_vm[0] }}
          cp -r /etc/nftables /tmp/{{ edpm_vm[0] }}
          cp -r /etc/os-net-config /tmp/{{ edpm_vm[0] }}
          ovs-vsctl list Open_vSwitch > /tmp/{{ edpm_vm[0] }}/ovs_vsctl_list_openvswitch.txt
          ip netns > /tmp/{{ edpm_vm[0] }}/ip_netns.txt
          ip a > /tmp/{{ edpm_vm[0] }}/network.txt
          ip ro ls >> /tmp/{{ edpm_vm[0] }}/network.txt
          rpm -qa > /tmp/{{ edpm_vm[0] }}/rpm_qa.txt
          podman images > /tmp/{{ edpm_vm[0] }}/podman_images.txt
          ausearch -i | grep denied > /tmp/{{ edpm_vm[0] }}/selinux-denials.log
          journalctl -p warning -t kernel -o short -g DROPPING --no-pager &> /tmp/{{ edpm_vm[0] }}/firewall-drops.txt
          EOF

    - name: Copy logs to host machine from edpm vm
      ignore_errors: true
      ci_script:
        output_dir: "{{ cifmw_artifacts_basedir }}/artifacts"
        script: |-
          scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -v -r -i {{ cifmw_artifacts_basedir }}/artifacts/edpm/ansibleee-ssh-key-id_rsa root@192.168.122.100:/tmp/{{ edpm_vm[0] }} {{ cifmw_artifacts_basedir }}/logs
