---
- name: Gather parameter passed to the playbook
  tags:
    - always
  ansible.builtin.copy:
    dest: "{{ cifmw_artifacts_basedir }}/artifacts/ansible-vars.yml"
    content: "{{ vars | to_nice_yaml }}"

- name: Gather facts
  tags:
    - always
  ansible.builtin.copy:
    dest: "{{ cifmw_artifacts_basedir }}/artifacts/ansible-facts.yml"
    content: "{{ ansible_facts | to_nice_yaml }}"

- name: Copy some network configuration files
  become: true
  ansible.builtin.shell:
    cmd: |-
      cp /etc/resolv.conf /etc/hosts {{ cifmw_artifacts_basedir }}/artifacts/
      cp -r /etc/NetworkManager/system-connections {{ cifmw_artifacts_basedir }}/artifacts/NetworkManager
      find {{ cifmw_artifacts_basedir }}/artifacts/NetworkManager -type f -exec chmod 0644 '{}' \;
      find {{ cifmw_artifacts_basedir }}/artifacts/NetworkManager -type d -exec chmod 0755 '{}' \;
      ip ro ls > {{ cifmw_artifacts_basedir }}/artifacts/ip-network.txt
      ip rule ls >> {{ cifmw_artifacts_basedir }}/artifacts/ip-network.txt
      ip -j -p link ls >> {{ cifmw_artifacts_basedir }}/artifacts/ip-network.txt
