- name: Run pre_package_build hooks
  vars:
    hooks: "{{ pre_package_build | default([]) }}"
  ansible.builtin.import_playbook: ./hooks.yml

- hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Build packages
      when:
        - cifmw_pkg_build_list is defined
        - cifmw_pkg_build_list | length > 0
      ansible.builtin.include_role:
        name: pkg_build
        tasks_from: build

- name: Run post_package_build hooks
  vars:
    hooks: "{{ post_package_build | default([]) }}"
  ansible.builtin.import_playbook: ./hooks.yml
