- name: Run pre_deploy hooks
  vars:
    hooks: "{{ pre_deploy | default([]) }}"
    step: pre_deploy
  ansible.builtin.import_playbook: ./hooks.yml

- name: Deploy podified control plane
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Load parameters files
      ansible.builtin.include_vars:
        dir: "{{ cifmw_basedir }}/artifacts/parameters"

    - name: Run edpm_prepare
      ansible.builtin.import_role:
        name: edpm_prepare

- name: Run post_ctlplane_deploy hooks
  vars:
    hooks: "{{ post_ctlplane_deploy | default([]) }}"
    step: post_ctlplane_deploy
  ansible.builtin.import_playbook: ./hooks.yml

- name: EDPM deployment on virtual baremetal
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Load parameters files
      ansible.builtin.include_vars:
        dir: "{{ cifmw_basedir }}/artifacts/parameters"

    - name: Create virtual baremetal and deploy EDPM
      when:
        - cifmw_edpm_deploy_baremetal | default('false') | bool
        - cifmw_deploy_edpm | default('false') | bool
      ansible.builtin.import_role:
        name: edpm_deploy_baremetal

- name: EDPM deployment on pre-provisioned VMs
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Load parameters files
      ansible.builtin.include_vars:
        dir: "{{ cifmw_basedir }}/artifacts/parameters"

    - name: Create VMs and Deploy EDPM
      when:
        - not cifmw_edpm_deploy_baremetal | default('false') | bool
        - cifmw_deploy_edpm | default('false') | bool
      block:
        - name: Create and provision external computes
          when:
            - cifmw_use_libvirt is defined
            - cifmw_use_libvirt | bool
          ansible.builtin.import_role:
            name: libvirt_manager
            tasks_from: deploy_edpm_compute.yml

        - name: Deploy EDPM
          ansible.builtin.import_role:
            name: edpm_deploy

- name: Run post_deploy hooks
  vars:
    hooks: "{{ post_deploy | default([]) }}"
    step: post_deploy
  ansible.builtin.import_playbook: ./hooks.yml
