- name: Run pre_admin_setup hooks
  vars:
    hooks: "{{ pre_admin_setup | default([]) }}"
    step: pre_admin_setup
  ansible.builtin.import_playbook: ./hooks.yml

- hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: false
  tasks:
    - name: Create openstack network elements
      ansible.builtin.import_role:
        name: os_net_setup

- name: Run post_admin_setup hooks
  vars:
    hooks: "{{ post_admin_setup | default([]) }}"
    step: post_admin_setup
  ansible.builtin.import_playbook: ./hooks.yml
