matrix:
  - name: Doc content
    aspell:
      lang: en
      ignore-case: true
      suggest: true
      sug-typo-analysis: true
    sources:
      - ./**/*.md
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.url:
      - pyspelling.filters.html:
    dictionary:
      wordlists:
        - docs/dictionary/en-custom.txt
      output: docs/_build/en-custom.dic
