---
- job:
    name: molecule
    nodeset:
      nodes:
        name: primary
        label: ansible-cloud-centos-9-stream-tiny
    parent: base-minimal
    pre-run: .zuul.d/prepare.yml
    run: .zuul.d/test-molecule.yml

- project:
    name: openstack-k8s-operators/ci-framework
    github-check:
      jobs:
        - molecule
