---
- job:
    name: molecule
    nodeset:
      nodes:
        name: controller
        label: centos-9-stream-crc-xl
    parent: base-crc
    vars:
      LC_ALL: en_US.utf8
      LANG: en_US.utf8
    pre-run: .zuul.d/molecule-prepare.yml
    run: .zuul.d/molecule-test.yml
    post-run: .zuul.d/collect-logs.yml

- job:
    name: end-to-end
    nodeset:
      nodes:
        name: controller
        label: centos-9-stream-crc-xxl
    vars:
      crc_parameters: "--memory 16000 --disk-size 120 --cpus 6"
    parent: base-crc
    pre-run: .zuul.d/e2e-prepare.yml
    run:
      - .zuul.d/dump_zuul_vars.yml
      - .zuul.d/e2e-run.yml
    post-run: .zuul.d/collect-logs.yml

- project:
    name: openstack-k8s-operators/ci-framework
    github-check:
      jobs:
        - molecule
        - end-to-end
