---
# Entry point for the CI Framework tool.
# Running by this playbook, and providing the needed information, you will
# be able to deploy various scenarios based on EDPM.
# Note that this playbook *must* be called from within
# openstack-k8s-operators/install_yaml repository in order to leverage its
# own methods.

- hosts: localhost
  gather_facts: true
  roles:
    - name: setup
    - name: repo_setup
  tasks:
    - name: "That's all folks"
      debug:
        msg: "For now at least"
    # TODO: add role inclusion with some conditional, such as "if we get
    # that specific setting, then include that role".
