---

- name: Reproducer Play
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  gather_facts: true
  pre_tasks:
    - name: Ensure we pass needed parameter
      ansible.builtin.assert:
        that:
          - cifmw_use_libvirt is defined
          - cifmw_use_libvirt | bool
        msg: >-
          Please ensure you pass "cifmw_use_libvirt: true" to the
          deployment!
        quiet: true
  roles:
    - role: ci_setup
    - role: libvirt_manager
    - role: reproducer
