---
- hosts: controller
  gather_facts: true
  tasks:
    - name: Run molecule
      environment:
        ANSIBLE_LOG_PATH: "{{ ansible_user_dir }}/zuul-output/logs/ansible-execution.log"
        MOLECULE_REPORT: "/tmp/report.html"
        LC_ALL: en_US.utf8
        LANG: en_US.utf8
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/ci_framework/roles/{{ TEST_RUN }}"
        cmd: "molecule -c {{ ansible_user_dir }}/{{ zuul.project.src_dir }}/.config/molecule/config_local.yml test --all"
