---
- name: List packages to install
  ansible.builtin.debug:
    var: cifmw_ci_setup_packages

- name: Install needed packages
  become: true
  ansible.builtin.package:
    name: "{{ cifmw_ci_setup_packages }}"
    state: latest
