- name: Get keystone data
  register: keystone_data
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  ansible.builtin.shell:
    cmd: oc get keystoneapi keystone -n openstack -o json

- name: Set keystone vars
  ansible.builtin.set_fact:
    keystone_secret_name: "{{ keystone_data.stdout | from_json | community.general.json_query('spec.secret') }}"
    keystone_passwd_select: "{{ keystone_data.stdout | from_json | community.general.json_query('spec.passwordSelectors.admin') }}"
    keystone_api: "{{ keystone_data.stdout | from_json | community.general.json_query('status.apiEndpoint.public') }}"

- name: Get credentials data
  register: os_password_data
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  ansible.builtin.shell:
    cmd: 'oc get secret {{ keystone_secret_name }} -n openstack -o json'

- name: Get password data
  ansible.builtin.set_fact:
    os_password: >-
      {{ os_password_data.stdout | from_json | community.general.json_query('data.' ~ keystone_passwd_select) | ansible.builtin.b64decode }}

- name: Get clouds.yaml
  ansible.builtin.template:
    src: clouds.yaml.j2
    dest: "{{ cifmw_tempest_artifacts_basedir }}/clouds.yaml"
