---
- name: Assert needed parameters are passed
  ansible.builtin.assert:
    quiet: true
    that:
      - cifmw_devscripts_ci_token is defined or
        cifmw_devscripts_ci_token_file is defined
      - not (cifmw_devscripts_ci_token is defined and
             cifmw_devscripts_ci_token_file is defined)
      - cifmw_devscripts_pull_secret is defined or
        cifmw_devscripts_pull_secret_file is defined
      - not (cifmw_devscripts_pull_secret is defined and
             cifmw_devscripts_pull_secret_file is defined)
    msg: >-
      Please provide either cifmw_devscripts_ci_token or
      cifmw_devscripts_ci_token_file
      and either cifmw_devscripts_pull_secret or
      cifmw_devscripts_pull_secret_file

- name: Get EPEL and install needed packages for dev-scripts
  tags:
    - packages
  vars:
    cifmw_ci_setup_epel_pkgs:
      - python3-bcrypt
      - python3-passlib
  ansible.builtin.import_role:
    name: ci_setup
    tasks_from: epel.yml

- name: Run devscripts role
  tags:
    - devscripts_layout
  vars:
    cifmw_devscripts_use_layers: true
  ansible.builtin.import_role:
    name: devscripts
