- job:
    name: cifmw-molecule-openshift_login
    nodeset: centos-9-crc-xl
- job:
    name: cifmw-molecule-openshift_provisioner_node
    nodeset: centos-9-crc-xl
- job:
    name: cifmw-molecule-openshift_setup
    nodeset: centos-9-crc-xl
- job:
    name: cifmw-molecule-rhol_crc
    nodeset: centos-9-crc-xl
