---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Converge
  hosts: all
  vars:
    cifmw_operator_build_dryrun: true
    cifmw_operator_build_push_ct: false
  tasks:
    - name: Build mariadb-operator
      include_role:
        name: operator_build
      vars:
        cifmw_operator_build_meta_build: true
        cifmw_operator_build_operators:
          - name: "mariadb-operator"
            src: "{{ ansible_user_dir }}/mariadb-operator"

    - name: Ensure that role output dict contains the expected values
      ansible.builtin.assert:
        that:
          # Check the explicit build operator
          - cifmw_operator_build_output['operators']['mariadb-operator']['commit_hash'] is defined
          - cifmw_operator_build_output['operators']['mariadb-operator']['image'] is defined
          - cifmw_operator_build_output['operators']['mariadb-operator']['image_bundle'] is defined
          - cifmw_operator_build_output['operators']['mariadb-operator']['image_storage_bundle'] is defined
          - cifmw_operator_build_output['operators']['mariadb-operator']['image_catalog'] is defined
          # Check the meta operator build output
          - cifmw_operator_build_output['operators']['openstack-operator']['commit_hash'] is defined
          - cifmw_operator_build_output['operators']['openstack-operator']['image'] is defined
          - cifmw_operator_build_output['operators']['openstack-operator']['image_bundle'] is defined
          - cifmw_operator_build_output['operators']['openstack-operator']['image_storage_bundle'] is defined
          - cifmw_operator_build_output['operators']['openstack-operator']['image_catalog'] is defined
