---
- name: Boostrap node
  ansible.builtin.import_playbook: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework/ci_framework/playbooks/01-bootstrap.yml"
- hosts: all
  tasks:
    - name: Run EDPM image builder
      tags:
        - edpm_build_img
      ansible.builtin.import_role:
        name: edpm_build_images
