---
- hosts: all
  tasks:
    - ansible.builtin.import_role:
        name: repo_setup
      vars:
       cifmw_repo_setup_output: "/etc/yum.repos.d/"
    - ansible.builtin.import_role:
        name: edpm_build_images
