---
- name: Boostrap node
  ansible.builtin.import_playbook: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework/ci_framework/playbooks/01-bootstrap.yml"
- hosts: all
  tasks:
    - name: Read hash from delorean.repo.md5 file
      tags:
        - edpm_build_img
      ansible.builtin.slurp:
        path: "{{ cifmw_basedir }}/artifacts/repositories/delorean.repo.md5"
      register: file_content

    - name: Set fact for cifmw_edpm_build_images_tag var
      tags:
        - edpm_build_img
      ansible.builtin.set_fact:
        cifmw_edpm_build_images_tag: "{{ file_content['content'] | b64decode | string | trim }}"

    - name: Run EDPM image builder
      tags:
        - edpm_build_img
      ansible.builtin.import_role:
        name: edpm_build_images
