---
- hosts: all
  gather_facts: true
  tasks:
    - name: Run EDPM build image
      environment:
        ANSIBLE_CONFIG: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework/ansible.cfg"
      ansible.builtin.command:
        chdir: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework"
        cmd: >-
          ansible-playbook ci/playbooks/edpm_build_images/edpm_image_builder.yml
          -e @scenarios/centos-9/base.yml
          {%- if cifmw_extras is defined %}
          {%-   for extra_vars in cifmw_extras %}
          -e "{{   extra_vars }}"
          {%-   endfor %}
          {%- endif %}
          -e @scenarios/centos-9/zuul_inventory.yml
          --tags packages
