---
- name: Bootstrap step
  ansible.builtin.import_playbook: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework/ci_framework/playbooks/01-bootstrap.yml"

- name: Deploy and run KUTTL operator tests
  hosts: "{{ cifmw_target_host | default('localhost') }}"
  tasks:
    - name: Download install_yamls deps
      ansible.builtin.include_role:
        name: 'install_yamls_makes'
        tasks_from: 'make_download_tools'

    - name: Run kuttl tests
      ansible.builtin.include_role:
        name: 'install_yamls_makes'
        tasks_from: 'make_{{ item }}_kuttl.yml'
      loop: "{{ cifmw_kuttl_tests_operator_list | default(['cinder' 'keystone']) }}"

- name: Run log related tasks
  ansible.builtin.import_playbook: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/ci-framework/ci_framework/playbooks/99-logs.yml"
