---
- hosts: all
  tasks:
    - name: Clone repos in the job workspace
      include_role:
        name: prepare-workspace

    - name: Install ansible-core
      become: true
      package:
        name: ansible-core
        state: present
