---
- hosts: all
  gather_facts: true
  tasks:
    - name: Ensure file is present
      register: molecule_report
      ansible.builtin.stat:
        path: /tmp/report.html
    - name: Manage molecule report file
      when:
        - molecule_report.stat.exists
      block:
        - name: Collect logs
          ansible.builtin.command:
            chdir: "{{ ansible_user_dir }}/zuul-output/logs"
            cmd: cp /tmp/report.html .

    - name: Check if we get ci-framework basedir
      register: cifmw_state
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/ci-framework"

    - name: Copy ci-framework interesting files
      when:
        - cifmw_state.stat.exists | bool
      ansible.builtin.shell:
        chdir: "{{ ansible_user_dir }}/zuul-output/logs/"
        cmd: |
          mkdir ci-framework; pushd ci-framework
          cp -ra {{ ansible_user_dir }}/ci-framework/logs . ;
          cp -ra {{ ansible_user_dir }}/ci-framework/artifacts . ;

    - name: Get some env related data
      ansible.builtin.shell: |
        rpm -qa | sort > {{ ansible_user_dir }}/zuul-output/logs/installed-pkgs.log;
        python --version > {{ ansible_user_dir }}/zuul-output/logs/python.log;
        pip3 --version >> {{ ansible_user_dir }}/zuul-output/logs/python.log;
        ansible --version >> {{ ansible_user_dir }}/zuul-output/logs/python.log;
        pip3 freeze >> {{ ansible_user_dir }}/zuul-output/logs/python.log;
        cp {{ ansible_user_dir }}/*.log {{ ansible_user_dir }}/zuul-output/logs/;

    - name: Copy files from workspace on node
      vars:
        work_dir: "{{ ansible_user_dir }}/workspace"
      ansible.builtin.include_role:
        name: fetch-output

    - name: Return artifact to Zuul
      when:
        - not skip_report | default(false)
        - molecule_report.stat.exists
      zuul_return:
        data:
          zuul:
            artifacts:
              - name: "Molecule report"
                url: "report.html"
                metadata:
                  type: html_report
