---
- hosts: all
  gather_facts: false
  tasks:
    - name: Prepare workspace
      ansible.builtin.include_role:
        name: prepare-workspace
    - name: Install required packages
      become: true
      ansible.builtin.package:
        name:
          - python3-pip
          - make
          - gcc
          - sudo
    - name: Install ansible requirements
      ansible.builtin.command: |
        make -C "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}" setup_molecule
