---
# Configure CRC from install_yamls directly
- name: Set some facts for later use
  set_fact:
    crc_configuration:  "{{ cifmw_rhol_crc_config_defaults | ansible.builtin.combine(cifmw_rhol_crc_config) }}"
    default_path: "{{ lookup('env', 'PATH', '/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin') }}"

- name: Cleanup if needed/wanted
  when:
    - "'crc' in vm_domains.list_vms"
    - cifmw_rhol_crc_force_cleanup|bool
  vars:
    make_crc_cleanup_dryrun: "{{ cifmw_rhol_crc_dryrun }}"
    make_crc_cleanup_env:
      PATH: "~/bin:{{ cifmw_rhol_crc_basedir }}/bin:{{ default_path }}"
  ansible.builtin.include_role:
    name: "install_yamls_makes"
    tasks_from: "make_crc_cleanup"

- name: Configure crc
  vars:
    make_crc_dryrun: "{{ cifmw_rhol_crc_dryrun }}"
    make_crc_env:
      PATH: "~/bin:{{ cifmw_rhol_crc_basedir }}/bin:{{ default_path }}"
      CPUS: "{{ crc_configuration['cpus'] }}"
      MEMORY: "{{ crc_configuration['memory'] }}"
      DISK: "{{ crc_configuration['disk-size'] }}"
    make_crc_params:
      CRC_URL: "{{ cifmw_rhol_crc_base_url }}/{{ cifmw_rhol_crc_tarball_name }}"
      KUBEADMIN_PWD: "{{ cifmw_rhol_crc_kubeadmin_pwd }}"
      PULL_SECRET: "{{ crc_configuration['pull-secret-file'] }}"
  ansible.builtin.include_role:
    name: "install_yamls_makes"
    tasks_from: "make_crc"

- name: Attach default network to CRC
  vars:
    make_crc_attach_default_interface_dryrun: "{{ cifmw_rhol_crc_dryrun }}"
    make_crc_attach_default_interface_env:
      PATH: "~/bin:{{ cifmw_rhol_crc_basedir }}/bin:{{ default_path }}"
  ansible.builtin.include_role:
    name: "install_yamls_makes"
    tasks_from: "make_crc_attach_default_interface"
