---
- name: Manage directories
  tags:
    - always
  ansible.builtin.file:
    path: "{{ cifmw_setup_basedir }}/{{ item }}"
    state: "{{ directory_state }}"
  loop:
    - artifacts
    - logs
    - tmp
    - volumes
  loop_control:
    label: "{{ cifmw_setup_basedir }}/{{ item }}"
