---
- name: Get DLRN hash
  ansible.builtin.get_url:
    url: "{{ cifwm_repo_setup_dlrn_uri }}/{{ cifmw_repo_setup_os_release }}{{ ansible_distribution_major_version }}-{{ cifmw_repo_setup_branch }}/{{ cifmw_repo_setup_promotion }}/delorean.repo.md5"
    dest: "{{ cifmw_repo_setup_basedir }}/artifacts/repositories/delorean.repo.md5"
