---
- name: Run repo-setup
  ansible.builtin.command:
    cmd: >-
      {{ cifmw_repo_setup_basedir }}/venv/bin/repo-setup
      {{ cifmw_repo_setup_promotion }}
      -b {{ cifmw_repo_setup_branch }}
      -o {{ cifmw_repo_setup_basedir }}/artifacts/repositories
