---
- name: Get repo-setup repository
  ansible.builtin.git:
    accept_hostkey: true
    dest: "{{ cifmw_repo_setup_basedir }}/repo-setup"
    repo: "https://github.com/ci-framework/repo-setup"

- name: Initialize python venv and install requirements
  ansible.builtin.pip:
    virtualenv: "{{ cifmw_repo_setup_basedir }}/venv"
    requirements: "{{ cifmw_repo_setup_basedir }}/repo-setup/requirements.txt"

- name: Install repo-setup package
  ansible.builtin.command:
    cmd: "{{ cifmw_repo_setup_basedir }}/venv/bin/python setup.py install"
    chdir: "{{ cifmw_repo_setup_basedir }}/repo-setup"
    creates: "{{ cifmw_repo_setup_basedir }}/venv/bin/repo-setup"

- name: Create repository output directory
  ansible.builtin.file:
    path: "{{ cifmw_repo_setup_basedir }}/artifacts/repositories"
    state: directory
