---
- name: Ensure directories are present
  ansible.builtin.file:
    path: "{{ cifmw_repo_setup_basedir }}/{{ item }}"
    state: directory
  loop:
    - tmp
    - artifacts/repositories
    - logs

- name: Make sure git-core package is installed
  become: true
  ansible.builtin.package:
    name: "git-core"
    state: present
  tags:
    - packages
    - bootstrap

- name: Get repo-setup repository
  ansible.builtin.git:
    accept_hostkey: true
    dest: "{{ cifmw_repo_setup_basedir }}/tmp/repo-setup"
    repo: "{{ cifmw_repo_setup_src }}"

- name: Initialize python venv and install requirements
  ansible.builtin.pip:
    virtualenv: "{{ cifmw_repo_setup_basedir }}/venv"
    requirements: "{{ cifmw_repo_setup_basedir }}/tmp/repo-setup/requirements.txt"
    virtualenv_command: "python3 -m venv"

- name: Install repo-setup package
  ci_script:
    output_dir: "{{ cifmw_repo_setup_basedir }}/artifacts"
    script: "{{ cifmw_repo_setup_basedir }}/venv/bin/python setup.py install"
    chdir: "{{ cifmw_repo_setup_basedir }}/tmp/repo-setup"
    creates: "{{ cifmw_repo_setup_basedir }}/venv/bin/repo-setup"
