name: Check pull request
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
jobs:
  run_linters:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install tox
      run: pip install tox>=4.0
    - name: Run tox linters
      run: tox -e linters
